version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutribot
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - nutribot-db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # локальный доступ к базе

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nutribot

      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

      # профиль можно добавить при необходимости
      # SPRING_PROFILES_ACTIVE: prod

    # по желанию:
    # ports:
    #   - "8080:8080"

volumes:
  nutribot-db-data:
