spring:
  application:
    name: nutribot-telegram
  profiles:
    default: local
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nutribot}
    username: ${DB_USERNAME:nutribot}
    password: ${DB_PASSWORD:nutribot}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}            # spring, hibernate, telegram etc.
    com.nutribot: ${LOGGING_LEVEL_APP:WARN}     # application
    org.flywaydb: ${LOGGING_LEVEL_FLYWAY:WARN}  # flyway

nutribot:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:}
  features:
    nutrient-explain:
      user-visible: ${TELEGRAM_NUTRIENT_EXPLAIN:false}